### PR TITLE
Use SAIPLL in order to provide the USB 48MHz clock

### PR DESCRIPTION
**Pull request by andreamerello**
Hi,

On my stm32f469 discovery board AFAICT the USB clock is quite off the nominal value (the ST reference manual mention 48MHz +/-0.25%, while I get more than 51MHz).

Currently I could not find any solution to derive a precise 48MHz clock from the main PLL without lowering clocks for the rest of system, so I'm synthesising the USB clock from the SAIPLL.

This makes the USB clock to be 48MHz, as it should. Looks like a reasonable solution to you ?

..I've also a patch for the kernel clk driver in my linux-stm32 repo in order to detect this configuration and modifying accordingly the clk tree..

### CODE REVIEW

**Comment by andreamerello** [comment]
..Another commit still about the 48MHz clock followed. Probably I should have used another branch in order to being able to create a separate pull request for it.. BTW with this (and driver in my linux-stm32 repo, branch stm32-sdio) the SDIO controller works for me.

**Comment by mcoquelin-stm32** [comment]
Thanks Andrea,
that looks really reasonable, thanks for your contribution.

You might share you Kernel patch with @bherrera, who also contributed to USB.

Regards,
Maxime

**Comment by andreamerello** [comment]
Well, the kernel patch for USB actually _is_ the one from @bherrera :) 

BTW I have another for SD card controller; It probably still needs some attention about something related to open-collector pad setting, then I will try to push it as a patch to the kernel ML..

**Comment by andreamerello** [comment]
Ah, maybe you meant the patch to the clk driver..will do :)

**Comment by pftbest** [comment]
Can you please explain it to me, you've got USB running with CPU clock set to 180MHz? I thought it is impossible to use USB with clock higher than 168MHz.

**Comment by bherrera** [comment]
Nice;) My patch for usb still need some rework to be accepted in mainline. I did not had the time to fix it.

For the sdcard I have some work in progress.  I can share with you guys.

**Comment by andreamerello** [comment]
@bherrera Cool! Yes, I would be definitively curious to give it a look :)

BTW I've got the SD working with my patches here [https://github.com/andreamerello/linux-stm32/commits/stm32-sdio](url)

Besically I've added some code for supporting the STM32 SDIO controller to the already existent mmci driver. It looks like it's just another variant of the same thing..

**Comment by andreamerello** [comment]
@pftbest While you cannot get a 48MHz clock for USB and maximum core clock at the same time from the primary PLL, it seems possible to  feed the core from the main PLL, at full clock speed, while feeding the USB with 48MHz clock from the secondary PLL.. This worked for me. Are you aware of any issues in this configuration ?

**Comment by andreamerello** [comment]
@bherrera [https://github.com/andreamerello/linux-stm32/commit/f208e3d79082d342488d51e2651d61477be2bfb2](url) here there is also the patch against the clk driver

**Comment by pftbest** [comment]
@andreamerello No, I've never seen this before, thats why I'm so surprised to learn that it actually works.

**Comment by bherrera** [comment]
@andreamerello sorry for the long delay in reply I was out of office for couple of days... My patch is still WIP for SDIO, but I could make it work with SDCard and WL1835MOD from TI. I had a quick look into you repo and seems you added lot more stuff that I did, so maybe I'm missing something...

[SDIO_WIP.txt](https://github.com/mcoquelin-stm32/afboot-stm32/files/476656/SDIO_WIP.txt)

**Comment by andreamerello** [comment]
.. Or maybe I've been too paranoid on certain things :)

Basically I've compared register description in the ST datasheet wrt
definitiond in the driver, and I tried to fix things where they differs,
either for missing registers or missing (reserved) bits..

Doing this, I could (hopefully) fix all I found out, except for one thing
about open-drain pad driving (I think I've placed a #warning, or at least a
comment, to remember looking into this).. This was why I've had not tried
to submit my patches yet :)

Beside that, where did you fine the amba id for our device?

Since the HW does not seem to provide one (I snooped in it's mmaped space,
and I couldn't find any), I reworked the driver to be able to work with
peripherals that does not have an amba ID, like other drivers seems to do
(probably it was tty pl011 that I looked at).. This is a noticeable portion
of my changes; but if it turns out that the device actually has an amba ID,
then I think we could go your way.

Andrea

**Comment by bherrera** [comment]
@andreamerello I could not also read the amba id from the peripheral. I used this "hackish" approach to by pass the ID verification/validation. This is not a valid one, I just increment the previous from ST. In fact ST does not mention the register address on their RM, and even when I try to forced the read on the ID address I always got 0x00. So your patch may be the right and good way. 

The other relevant change I got from EMCRAFT linux: [https://github.com/EmcraftSystems/linux-emcraft/commit/04851d0815be8c177cfb94abafd2a9d7cc433ee3](url)

**Pull request merged**
